### ISSUE TITLE
Home brew Error

### ISSUE THREAD

**Issue by Laxman-SM** [minamijoyo/homebrew-tfschema#2]
Resolving deltas: 100% (11/11), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/minamijoyo/homebrew-tfschema/tfschema.rb
formulae require at least a URL
Error: Cannot tap minamijoyo/tfschema: invalid syntax in tap!

I'm getting above mentioned error during "brew install minamijoyo/tfschema/tfschema" execution

**Comment by minamijoyo** [comment]
@Laxman-SM Thank you for reporting this!

The error looks similar to the following: https://github.com/minamijoyo/tfupdate/issues/55
Do you use brew on M1 or M2 mac?

**Comment by Laxman-SM** [comment]
@minamijoyo  Thank you for your reply!
Yes, I'm using brew on M1. and Homebrew version is 3.5.3
Homebrew/homebrew-core (git revision 901adf4d43f; last commit 2022-07-05)
Homebrew/homebrew-cask (git revision 3dcdab047f; last commit 2022-07-05)

**Comment by Laxman-SM** [comment]
@minamijoyo  Thanks you. I retried.

brew install minamijoyo/tfschema/tfschema
Warning: No available formula or cask with the name “minamijoyo/tfschema/tfschema”. Did you mean minamijoyo/hcledit/hcledit?
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
brew search minamijoyo
==> Formulae
minamijoyo/hcledit/hcledit :heavy_check_mark:             minamijoyo/tfupdate/tfupdate :heavy_check_mark:            minicom

seems no formula available for tfschema.

**Comment by minamijoyo** [comment]
Thank you for your confirmation.
